# Generated by Django 5.0.2 on 2024-03-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='solution',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='issue',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='issue',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='associated_project',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='devs',
        ),
        migrations.AddField(
            model_name='log',
            name='resolved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='log',
            name='resolved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectDevs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ManyToManyField(related_name='dev_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ResolvedTicket',
        ),
    ]
